// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {bilibili} from '../models';

export function AddAudioToList(arg1:string,arg2:string):Promise<void>;

export function AddCollectionToList(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function AddCompilationToList(arg1:string,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function AddProfileVideoToList(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function AddVideoToList(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreatVideoList():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetListCount(arg1:string):Promise<number>;

export function GetTheme():Promise<string>;

export function LoadVideoList(arg1:string):Promise<services.VideoList>;

export function QueryAudio(arg1:string):Promise<bilibili.Audio>;

export function QueryCollection(arg1:string):Promise<bilibili.FavList>;

export function QueryCompilation(arg1:number,arg2:number):Promise<bilibili.CompliationInformation>;

export function QueryProfileVideo(arg1:string):Promise<number>;

export function QueryVideo(arg1:string):Promise<bilibili.Video>;

export function SaveVideoList(arg1:services.VideoList,arg2:string):Promise<void>;

export function TidyVideoList(arg1:string):Promise<void>;
