// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAudioToList(arg1, arg2) {
  return window['go']['wails_api']['WailsApi']['AddAudioToList'](arg1, arg2);
}

export function AddCollectionToList(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['WailsApi']['AddCollectionToList'](arg1, arg2, arg3, arg4);
}

export function AddCompilationToList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails_api']['WailsApi']['AddCompilationToList'](arg1, arg2, arg3, arg4, arg5);
}

export function AddProfileVideoToList(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['WailsApi']['AddProfileVideoToList'](arg1, arg2, arg3, arg4);
}

export function AddVideoToList(arg1, arg2, arg3) {
  return window['go']['wails_api']['WailsApi']['AddVideoToList'](arg1, arg2, arg3);
}

export function Checkffmpeg() {
  return window['go']['wails_api']['WailsApi']['Checkffmpeg']();
}

export function DownloadTaskList() {
  return window['go']['wails_api']['WailsApi']['DownloadTaskList']();
}

export function GetAppVersion() {
  return window['go']['wails_api']['WailsApi']['GetAppVersion']();
}

export function GetFavCollect(arg1) {
  return window['go']['wails_api']['WailsApi']['GetFavCollect'](arg1);
}

export function GetListCount() {
  return window['go']['wails_api']['WailsApi']['GetListCount']();
}

export function GetTaskListAll() {
  return window['go']['wails_api']['WailsApi']['GetTaskListAll']();
}

export function GetTaskListPage(arg1) {
  return window['go']['wails_api']['WailsApi']['GetTaskListPage'](arg1);
}

export function GetTheme() {
  return window['go']['wails_api']['WailsApi']['GetTheme']();
}

export function GetUserInf() {
  return window['go']['wails_api']['WailsApi']['GetUserInf']();
}

export function GetUsersCollect() {
  return window['go']['wails_api']['WailsApi']['GetUsersCollect']();
}

export function LoadConfig() {
  return window['go']['wails_api']['WailsApi']['LoadConfig']();
}

export function QueryAudio(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryAudio'](arg1);
}

export function QueryCollection(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryCollection'](arg1);
}

export function QueryCompilation(arg1, arg2) {
  return window['go']['wails_api']['WailsApi']['QueryCompilation'](arg1, arg2);
}

export function QueryProfileVideo(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryProfileVideo'](arg1);
}

export function QueryVideo(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryVideo'](arg1);
}

export function RefreshConfig() {
  return window['go']['wails_api']['WailsApi']['RefreshConfig']();
}

export function ResetConfig() {
  return window['go']['wails_api']['WailsApi']['ResetConfig']();
}

export function ResetDownloadList() {
  return window['go']['wails_api']['WailsApi']['ResetDownloadList']();
}

export function SaveConfig(arg1) {
  return window['go']['wails_api']['WailsApi']['SaveConfig'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails_api']['WailsApi']['Startup'](arg1);
}
