// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAudioToList(arg1, arg2) {
  return window['go']['wails_api']['WailsApi']['AddAudioToList'](arg1, arg2);
}

export function AddCollectionToList(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['WailsApi']['AddCollectionToList'](arg1, arg2, arg3, arg4);
}

export function AddCompilationToList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails_api']['WailsApi']['AddCompilationToList'](arg1, arg2, arg3, arg4, arg5);
}

export function AddProfileVideoToList(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['WailsApi']['AddProfileVideoToList'](arg1, arg2, arg3, arg4);
}

export function AddVideoToList(arg1, arg2, arg3) {
  return window['go']['wails_api']['WailsApi']['AddVideoToList'](arg1, arg2, arg3);
}

export function CreatVideoList() {
  return window['go']['wails_api']['WailsApi']['CreatVideoList']();
}

export function GetAppVersion() {
  return window['go']['wails_api']['WailsApi']['GetAppVersion']();
}

export function GetListCount(arg1) {
  return window['go']['wails_api']['WailsApi']['GetListCount'](arg1);
}

export function GetTheme() {
  return window['go']['wails_api']['WailsApi']['GetTheme']();
}

export function LoadVideoList(arg1) {
  return window['go']['wails_api']['WailsApi']['LoadVideoList'](arg1);
}

export function QueryAudio(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryAudio'](arg1);
}

export function QueryCollection(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryCollection'](arg1);
}

export function QueryCompilation(arg1, arg2) {
  return window['go']['wails_api']['WailsApi']['QueryCompilation'](arg1, arg2);
}

export function QueryProfileVideo(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryProfileVideo'](arg1);
}

export function QueryVideo(arg1) {
  return window['go']['wails_api']['WailsApi']['QueryVideo'](arg1);
}

export function SaveVideoList(arg1, arg2) {
  return window['go']['wails_api']['WailsApi']['SaveVideoList'](arg1, arg2);
}

export function TidyVideoList(arg1) {
  return window['go']['wails_api']['WailsApi']['TidyVideoList'](arg1);
}
