// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Checkffmpeg() {
  return window['go']['main']['App']['Checkffmpeg']();
}

export function GetFavCollect(arg1) {
  return window['go']['main']['App']['GetFavCollect'](arg1);
}

export function GetUserInf() {
  return window['go']['main']['App']['GetUserInf']();
}

export function GetUsersCollect() {
  return window['go']['main']['App']['GetUsersCollect']();
}

export function ListDownload(arg1, arg2) {
  return window['go']['main']['App']['ListDownload'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoginBilibili() {
  return window['go']['main']['App']['LoginBilibili']();
}

export function OpenDownloadFolader() {
  return window['go']['main']['App']['OpenDownloadFolader']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RefreshConfig() {
  return window['go']['main']['App']['RefreshConfig']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveVideoListTo(arg1) {
  return window['go']['main']['App']['SaveVideoListTo'](arg1);
}

export function SetDownloadPathDialog() {
  return window['go']['main']['App']['SetDownloadPathDialog']();
}
