// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bilibili} from '../models';
import {config} from '../models';
import {services} from '../models';

export function GetFavCollect(arg1:number):Promise<bilibili.Collects>;

export function GetUserInf():Promise<bilibili.AccountInformation>;

export function GetUsersCollect():Promise<bilibili.Collects>;

export function LoadConfig():Promise<config.Config>;

export function LoginBilibili():Promise<void>;

export function OpenDownloadFolader():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function RefreshConfig():Promise<void>;

export function ResetConfig():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveVideoListTo(arg1:services.VideoList):Promise<void>;

export function SetDownloadPathDialog():Promise<void>;
