// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.Config>;

export function MakeAndSaveList(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function MakeUpEditor():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SearchFavListInformation(arg1:string):Promise<main.FavList>;

export function StartDownload(arg1:main.DownloadOption):Promise<void>;
