// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AudioDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function Checkffmpeg() {
  return window['go']['main']['App']['Checkffmpeg']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetVideoList() {
  return window['go']['main']['App']['GetVideoList']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoginBilibili() {
  return window['go']['main']['App']['LoginBilibili']();
}

export function MakeAndSaveList(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeAndSaveList'](arg1, arg2, arg3);
}

export function QueryFavCollect() {
  return window['go']['main']['App']['QueryFavCollect']();
}

export function RefreshConfig() {
  return window['go']['main']['App']['RefreshConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveVideoList(arg1) {
  return window['go']['main']['App']['SaveVideoList'](arg1);
}

export function SearchFavListInformation(arg1) {
  return window['go']['main']['App']['SearchFavListInformation'](arg1);
}

export function SearchSongInformation(arg1) {
  return window['go']['main']['App']['SearchSongInformation'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
