// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadList(arg1, arg2) {
  return window['go']['main']['App']['DownloadList'](arg1, arg2);
}

export function MakeAndSaveList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeAndSaveList'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchFavListInformation(arg1) {
  return window['go']['main']['App']['SearchFavListInformation'](arg1);
}
