name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails App (macOS)
        if: matrix.os == 'macos-latest'
        run: wails build -compiler clang -platform darwin/amd64,darwin/arm64

      - name: Build Wails App (Windows)
        if: matrix.os == 'windows-latest'
        run: wails build -compiler gcc -platform windows/amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BADownloader-${{ matrix.os }}
          path: build/bin/*
